class Items {
	
}

Items.getItems = function(num) {
	
if(num == 1) return	"A Blue Slide";
if(num == 2) return "A Satellite Dish";
if(num == 3) return "A Poinsettia";
if(num == 4) return "\"Smokes Tbone Slump\" grafitti";
if(num == 5) return "A Nativity Scene";
if(num == 6) return "Entrada";
if(num == 7) return "A Doctor/Dentist Office";
if(num == 8) return "FACP Inside";
if(num == 9) return "Student Station";
if(num == 10) return "A Tree with little to no leaves";
if(num == 11) return "A Palm Tree";
if(num == 12) return "Taipet Café";
if(num == 13) return "Letter To Santa";
if(num == 14) return "No Golfing";
if(num == 15) return "Use Other Door";
if(num == 16) return "A Green Water Fountain";
if(num == 17) return "Police next to Fire Dept";
if(num == 18) return "2-Person Chest Press";
if(num == 19) return "A Nutcracker";
if(num == 20) return "License Plate 4MM1449";
if(num == 21) return "Icicle Christmas Lights";
if(num == 22) return "No Outlet";
if(num == 23) return "Deflated Christmas Decorations";
if(num == 24) return "A Manhole Cover";
if(num == 25) return "Be Kind";
if(num == 26) return "Locker 492";
if(num == 27) return "Private Property";
if(num == 28) return "A Padlock";
if(num == 29) return "Rowland Elementary School";
if(num == 30) return "Not A Through Street";
if(num == 31) return "A Security Camera";
if(num == 32) return "A Gree Basketball Court";
if(num == 33) return "A Liquor Store (from the outside!!)";
if(num == 34) return "Tobacco Free Facility";
if(num == 35) return "A Large White Cross";
if(num == 36) return "End County Maintenance Road";
if(num == 37) return "A Stone Bench (without a table attached)";
if(num == 38) return "A Fire Hydrant";
if(num == 39) return "A Florist";
if(num == 40) return "Princess Leah";
if(num == 41) return "An \"End\" Sign";
if(num == 42) return "A Frog Near A Snail";
if(num == 43) return "An Empty Lot";
if(num == 44) return "A Messy Front Yard";
if(num == 45) return "Room C4";
if(num == 46) return "The Christian Flag";
if(num == 47) return "Blandford Elementary";
if(num == 48) return "An Apartment Building";
if(num == 49) return "No Dumping";
if(num == 50) return "A Payphone";
if(num == 51) return "A Canopy That Says \"Security\"";
if(num == 52) return "Christmas Bells";
if(num == 53) return "A Parking Spot for Paris Yu";
if(num == 54) return "A door with both a door knob and a door handle";
if(num == 55) return "A Boat";
if(num == 56) return "Beware of Dog";
if(num == 57) return "18222";
if(num == 58) return "La Guardia & Sierra Leone";
if(num == 59) return "Peter Lin\'s School Picture";
if(num == 60) return "A White Fence";
if(num == 61) return "\"Southland\" (no s on the end)";
if(num == 62) return "Ms. Aguirre\'s Room";
if(num == 63) return "A Gas Station";
if(num == 64) return "A BBQ Grill";
if(num == 65) return "All You Can Eat";
if(num == 66) return "Birds Of Paradise";
if(num == 67) return "A Sundial";
if(num == 68) return "A Building with a Rectangular Roof";
if(num == 69) return "23 above 15";
if(num == 70) return "A Wreath On A Door";
if(num == 71) return "An Anti-Bully Poster";
if(num == 72) return "Ball Diamond Rental";
if(num == 73) return "Dolphins";
if(num == 74) return "Red Bricks That Don\'t Follow the Placement Pattern";
if(num == 75) return "A Shopping Cart";
if(num == 76) return "Rowland Pony Baseball";
if(num == 77) return "A Pothole";
if(num == 78) return "A Basketball Hoop In The Front Yard";
if(num == 79) return "A Covered Vehicle";
if(num == 80) return "A Two-Story House";
if(num == 81) return "A Storage Shed";
if(num == 82) return "\"Excellence\" Banner";
if(num == 83) return "A Blue Prius";
if(num == 84) return "Room 80";
if(num == 85) return "Santa Ysabela";
if(num == 86) return "A picture that has at least 100 people";
if(num == 87) return "Los Padres & Farjardo";
if(num == 88) return "Jeff Annoreno Fitness Center";
if(num == 89) return "A Blue Trashcan";
if(num == 90) return "First-Time Visitor";
if(num == 91) return "A Mural With Birds";
if(num == 92) return "A Tree with Candy Cane Decorations";
if(num == 93) return "Going Out Of Business";
if(num == 94) return "Cactus";
if(num == 95) return "Men's & Women's Bathroom next to each other";
if(num == 96) return "A Scarecrow";
if(num == 97) return "A Soccer Goal";
if(num == 98) return "Huskee";
if(num == 99) return "18500";
if(num == 100) return "*Take a photo with your ENTIRE team and an SCS Main Office worker*";
	return "";

}